_recursive_: true
_target_: pytorch_lightning.Trainer
enable_checkpointing: true
gpus: 1
max_epochs: 500
min_epochs: 10
val_check_interval: 1.0
log_every_n_steps: 50
benchmark: false
deterministic: true
