defaults:
  - embedding: unet_encoder
  - optimizer: adam
  - output: unet_decoder
  - scheduler: plateau
  - transformer: self_attention

_recursive_: False
_target_: poet.models.transformer_unet.TransformerUnet
n_transformers: 1
transformer_depth: 3
output_channels: 1
loss_str: kernel_crps
learning_rate: ${learning_rate}
ens_mems: ${data.ens_mems}
grid_dims: ${data.grid_dims}
